//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaminabeBlazor.Web.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaminabeBlazor.Web.Shared.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}の為、{1}できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CanNotExecute {
            get {
                return ResourceManager.GetString("CanNotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteConfirm {
            get {
                return ResourceManager.GetString("ExecuteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な要求です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HttpStatusCode400 {
            get {
                return ResourceManager.GetString("HttpStatusCode400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証情報が無効です。
        ///再度認証を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HttpStatusCode401 {
            get {
                return ResourceManager.GetString("HttpStatusCode401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputPlaceHolder {
            get {
                return ResourceManager.GetString("InputPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}から{2}の範囲で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegularHalfAlphaNum {
            get {
                return ResourceManager.GetString("RegularHalfAlphaNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は取得されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnGeted {
            get {
                return ResourceManager.GetString("UnGeted", resourceCulture);
            }
        }
    }
}
