//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaminabeBlazor.Web.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WordResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaminabeBlazor.Web.Shared.Resources.WordResource", typeof(WordResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランドマスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Brand_Master {
            get {
                return ResourceManager.GetString("Brand_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Calc {
            get {
                return ResourceManager.GetString("Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリマスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category_Master {
            get {
                return ResourceManager.GetString("Category_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CautionInfo {
            get {
                return ResourceManager.GetString("CautionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代表者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ceo {
            get {
                return ResourceManager.GetString("Ceo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回収日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionDate {
            get {
                return ResourceManager.GetString("CollectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回収日区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionDateType {
            get {
                return ResourceManager.GetString("CollectionDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回収日区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionDateTypeName {
            get {
                return ResourceManager.GetString("CollectionDateTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompleteInfo {
            get {
                return ResourceManager.GetString("CompleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先マスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Customer_Master {
            get {
                return ResourceManager.GetString("Customer_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先名カナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomerKanaName {
            get {
                return ResourceManager.GetString("CustomerKanaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先略名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomerShortName {
            get {
                return ResourceManager.GetString("CustomerShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   締日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutoffDate {
            get {
                return ResourceManager.GetString("CutoffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   締日区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutoffDateType {
            get {
                return ResourceManager.GetString("CutoffDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   締日区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutoffDateTypeName {
            get {
                return ResourceManager.GetString("CutoffDateTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMode {
            get {
                return ResourceManager.GetString("EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設立年月日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EstablishmentDate {
            get {
                return ResourceManager.GetString("EstablishmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタ条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterCondition {
            get {
                return ResourceManager.GetString("FilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホームページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kana {
            get {
                return ResourceManager.GetString("Kana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定価 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListPrice {
            get {
                return ResourceManager.GetString("ListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインＩＤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginId {
            get {
                return ResourceManager.GetString("LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メンテナンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受注 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受注伝票作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order_Receipt_Create {
            get {
                return ResourceManager.GetString("Order_Receipt_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受注伝票一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order_Receipt_List {
            get {
                return ResourceManager.GetString("Order_Receipt_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続きを表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PagingText {
            get {
                return ResourceManager.GetString("PagingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品マスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Product_Master {
            get {
                return ResourceManager.GetString("Product_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductTag {
            get {
                return ResourceManager.GetString("ProductTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リピーター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repeater {
            get {
                return ResourceManager.GetString("Repeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   四捨五入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   略名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税計算区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxCalcType {
            get {
                return ResourceManager.GetString("TaxCalcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税計算区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxCalcTypeName {
            get {
                return ResourceManager.GetString("TaxCalcTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税端数処理区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxRoundType {
            get {
                return ResourceManager.GetString("TaxRoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税端数処理区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxRoundTypeName {
            get {
                return ResourceManager.GetString("TaxRoundTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxType {
            get {
                return ResourceManager.GetString("TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxTypeName {
            get {
                return ResourceManager.GetString("TaxTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
